kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: gpu-admission
  labels:
    k8s-app: gpu-admission
rules:
# rules for gpu-admssion
- apiGroups: [""] # "" indicates the core API group
  resources: ["configmaps", "namespaces", "nodes", "pods"]
  verbs: ["get", "watch", "list"]
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods"]
  verbs: ["update", "patch"]
# extra rules for kubernetes-scheduler
- apiGroups: ["storage.k8s.io"]
  resources: ["storageclasses", "csinodes"]
  verbs: ["get", "watch", "list"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: gpu-admission
  labels:
    k8s-app: gpu-admission
roleRef:
  kind: Role
  name: gpu-admission
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: gpu-admission
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: gpu-admission-system
  labels:
    k8s-app: gpu-admission
roleRef:
  kind: ClusterRole
  name: system:kube-scheduler
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: gpu-admission
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: gpu-admission
  labels:
    k8s-app: gpu-admission
