apiVersion: v1
kind: ConfigMap
metadata:
  name: gpu-admission-config
data:
  policy.json: |-
    {
      "kind": "Policy",
      "apiVersion": "v1",
      "predicates": [
        {
          "name": "PodFitsHostPorts"
        },
        {
          "name": "PodFitsResources"
        },
        {
          "name": "NoDiskConflict"
        },
        {
          "name": "MatchNodeSelector"
        },
        {
          "name": "HostName"
        }
      ],
      "priorities": [
        {
          "name": "BalancedResourceAllocation",
          "weight": 1
        },
        {
          "name": "ServiceSpreadingPriority",
          "weight": 1
        }
      ],
      "extenders": [
        {
          "urlPrefix": "http://127.0.0.1:10251/scheduler",
          "apiVersion": "v1beta1",
          "filterVerb": "predicates",
          "enableHttps": false,
          "nodeCacheCapable": false
        }
      ],
      "hardPodAffinitySymmetricWeight": 10,
      "alwaysCheckAllPredicates": false
    }
  gpu-admission.json: |-
    {
      "QuotaConfigMapName": "gpu-admission-quota",
      "QuotaConfigMapNamespace": "kube-system",
      "GPUModelLabel": "gaia.tencent.com/gpu-model",
      "GPUPoolLabel": "gaia.tencent.com/gpu-pool"
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gpu-scheduler
  labels:
    app: gpu-admission
spec:
  selector:
    matchLabels:
      app: gpu-admission
  replicas: 1
  template:
    metadata:
      labels:
        app: gpu-admission
    spec:
      containers:
      - name: kube-scheduler
        # image: gcr.io/google_containers/hyperkube:v1.14.10
        # imagePullPolicy: IfNotPresent
        image: asia.gcr.io/olli-iviet/kube-scheduler:v1.14.10-a
        imagePullPolicy: IfNotPresent
        args:
        - kube-scheduler
        - --policy-config-file=/gpu-admission-config/policy.json
        - --address=0.0.0.0
        - --leader-elect=false
        - --scheduler-name=gpu-scheduler
        - -v=4
        livenessProbe:
          httpGet:
            path: /healthz
            port: 10251
          initialDelaySeconds: 15
        readinessProbe:
          httpGet:
            path: /healthz
            port: 10251
        volumeMounts:
        - name: gpu-admission-config
          mountPath: /gpu-admission-config
      - name: gpu-admission
        image: asia.gcr.io/olli-iviet/gpu-admission
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3456
        command:
        - /gpu-admission
        - --config=/gpu-admission-config/gpu-admission.json
        - --address=0.0.0.0:3456
        - --v=4
        livenessProbe:
          httpGet:
            path: /version
            port: 3456
        readinessProbe:
          httpGet:
            path: /version
            port: 3456
        volumeMounts:
        - name: gpu-admission-config
          mountPath: /gpu-admission-config
      serviceAccountName: gpu-admission
      volumes:
      - name: gpu-admission-config
        configMap:
          name: gpu-admission-config
